config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  post 'download', to: 'home#download'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def download
    @results = adapter.results
    if @results.empty?
      flash[:notice] = 'nothing was found'

      return render :index
    end

    create_tmp_file
    send_file csv_file_path, type: 'text/csv'
  end

  private

  def adapter
    GoogleAPI::GoogleAPIAdapter.new(params[:request], params[:count].to_i)
  end

  def create_tmp_file
    FileUtils.mkdir_p dir_name
    CSV.open(csv_file_path, 'wb') do |csv|
      csv << ['Title', 'Description', 'Subscribers amount', 'Email']
      @results.each do |result|
        row = [result.title, result.description, result.subscribers_amount,
               result.email]

        csv << row
      end
    end
  end

  def csv_file_path
    time_str = DateTime.now.strftime('%m_%d_%Y_%H_%M_%S')
    @path ||= "#{dir_name}/results_#{time_str}.csv"
  end

  def dir_name
    '/tmp/youtube_channels_collection'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container tetx-center m-2">
  <% if flash[:notice] %>
    <div class="alert alert-info pl-2 pr-2"><%= flash[:notice] %></div>
  <% end %>

  <%= form_with url: download_path, local: true do |form| %>
    <div class="form-group pr-2 pl-2">
      <%= form.text_field :request, class: 'form-control', placeholder: 'put your request here', required: true %>
    </div>

    <div class="form-group pr-2 pl-2">
      <%= form.text_field :count, class: 'form-control', placeholder: 'minimum count of records', required: true %>
    </div>

    <div class="form-group pr-2 pl-2">
      <%= form.submit 'get results', data: { disable_with: false }, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubeChannelsCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>